name: SystemIdentification
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - colorama=0.4.4
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - decorator=5.0.9
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2021.3.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jpeg=9b
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.1.3
  - prompt-toolkit=3.0.17
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.9.0
  - pywin32=227
  - pyzmq=20.0.0
  - qt=5.9.7
  - scipy=1.6.1
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - autograd==1.3
    - future==0.18.2
    - imageio==2.9.0
    - joblib==1.0.1
    - mpmath==1.2.1
    - opencv-python==4.5.3.56
    - scikit-learn==0.24.2
    - sklearn==0.0
    - sympy==1.7.1
    - threadpoolctl==2.1.0
