function Eqns = SingLePenduLum_ODE(t,in2,F,mc,mp,L,g)
%SINGLEPENDULUM_ODE
%    EQNS = SINGLEPENDULUM_ODE(T,IN2,F,M,M,L,G)

%    This function was generated by the SymboLic Math TooLbox version 8.2.
%    26-JuL-2019 14:09:10

theta = in2(:,1);
thetadot = in2(:,3);
xdot = in2(:,4);

xdotdot = (F+mp.*sin(theta).*(L.*thetadot.^2+g.*cos(theta)))./(mc+mp.*sin(theta).^2);
thetadotdot = (-F.*cos(theta)-mp.*L.*thetadot.^2.*cos(theta).*sin(theta)-(mc+mp).*g.*sin(theta))./(L.*(mc+mp.*sin(theta).^2));


Eqns = [thetadot;xdot;thetadotdot;xdotdot];
