function Sindy_ODEs = Sindy_ODE_RHS(t,in2,u1)
%SINDY_ODE_RHS
%    SINDY_ODES = SINDY_ODE_RHS(T,IN2,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Sep-2021 03:24:50

z1 = in2(:,1);
z2 = in2(:,2);
z3 = in2(:,3);
z4 = in2(:,4);
t2 = cos(z1);
t3 = sin(z1);
t4 = z1.*2.0;
t5 = z1.*2.0;
t6 = z1.^2;
t7 = z3.^2;
t8 = cos(t5);
t9 = sin(t5);
t10 = cos(t4);
t11 = sin(t4);
Sindy_ODEs = [z3;z4;(t10.*5.8305e+5+u1.*3.0029e+5-cos(z2.*2.0).*6.2715e+3-cos(z1+1.106299999999464).*3.7329e+6-cos(z3).*1.7086e+4+t6.*t11.*3.543e+6+t7.*t11.*5.349e+4+1.0852e+6)./(t10.*1.615e+5+cos(z3.*2.0).*8.119e+3+cos(z1-3.198799999995572e-2).*4.4777e+5-8.3038e+5);(t2.*-2.5062e+5-t3.*2.8855e+7+t8.*1.24945e+5+t9.*1.4079e+7-u1.*1.0e+5+t2.*t6.*1.2046e+5+t3.*t6.*1.1576e+7-t3.*t7.*1.0178e+5+t6.*t9.*1.66055e+6+t7.*t9.*3.668e+4+1.24945e+5)./(t8.*3.50405e+4-1.265795e+5)];
