function Sindy_ODEs = Sindy_ODE_RHS(t,in2,in3)
%SINDY_ODE_RHS
%    SINDY_ODES = SINDY_ODE_RHS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Sep-2021 22:29:43

z1 = in2(1,:);
z2 = in2(2,:);
z3 = in2(3,:);
z4 = in2(4,:);
t2 = z1.*2.0;
t3 = z2.*-1.0;
t4 = z2.*1.0;
t5 = z2.*-2.0;
t6 = z2.*2.0;
t7 = t3+z1;
t8 = t5+z1;
t12 = t2+t3;
t9 = cos(t7);
t10 = sin(t7);
t11 = sin(t8);
t13 = sin(t12);
t14 = t9.^2;
Sindy_ODEs = [z3.*9.973970543791921e-1;z4.*9.993696964861982e-1;(t10.*5.944593e+6+t11.*3.829026e+7+t13.*6.032977e+6-sin(t2+t5).*5.819615e+6+sin(z1).*5.427694e+7+t10.*z4.^2.*3.839832e+6)./(t14.*7.733497e+6-1.0e+7);((t10.*-7.040830490242769e-1+t11.*1.300627678695719+t13.*6.706128500608543-sin(z2).*5.614081815161626+t10.*z3.^2.*7.589236329688447e-1).*-1.0)./(t14-1.128759775950869)];
